---
title: "benthic_recovery_analysis"
author: "CEB"
date: '2023-05-12'
output: html_document
---


#load packages
```{r}
library(tidyverse)
library(vegan)
library(cowplot)
library(brms)
library(jtools)
library(tidybayes)
library(emmeans)

```


#set plot theme
```{r}
theme_casey<-
  theme_bw()+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        text = element_text(size = 14, family = "Arial"),
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA)
        )

theme_set(theme_casey) #THIS IS KEY*****
  
  
```



#load data
```{r}
#benthic data: 
load("../data/R_data/benthic_group_data.Rdata")
#broad groups: 
#uvc_dat_group_trans_wide_prop #broad groups, proportion cover, transect, wide
#uvc_dat_group_isl_wide #broad groups, % cover, island-level, wide
#benthic_dist_mat_bray_diff_no15 #for dissimilarity analysis - island-level
```



#Run BRMS model for benthic groups
```{r}

#and add a constant so can use beta regression (no 0s)----
#from Douma and Weedon 2019 (Appendix S3)
#136 = length(x) = total number of samples

transform01 <- function(x) {
  (x * (136 - 1) + 0.5) / (136)
}

uvc_dat_group_trans_wide_prop_scale2<-
  uvc_dat_group_trans_wide_prop %>%
  mutate_at(6:14, transform01)

uvc_dat_group_trans_wide_prop_scale2


#set up multivariate model: 
benthic_mv_isl_beta<-
  bf(mvbind(Hard_coral, CCA, Pavement, Halimeda, Rubble) ~ Treatment*Year + (1|Atoll/Island),                   
     family = Beta())
#should i include correlate effects of atoll and island - see vignette https://cran.r-project.org/web/packages/brms/vignettes/brms_multivariate.html

#set prior:
benthic_prior_bb = 
  #Halimeda: expect higher proportions in 2018, and higher around birdy islands. other than that not sure: 
  set_prior("normal(-1,1)", class = "b", coef = "TreatmentRatty", resp = "Halimeda") +
  set_prior("normal(1,1)", class = "b", coef = "Year2018", resp = "Halimeda") +
  set_prior("normal(0,1)", class = "b", coef = "Year2021", resp = "Halimeda") +
  set_prior("normal(-1,1)", class = "b", coef = "TreatmentRatty:Year2018", resp = "Halimeda") +
  set_prior("normal(0,1)", class = "b", coef = "TreatmentRatty:Year2021", resp = "Halimeda") +
    #CCA: same as Halimeda
  set_prior("normal(-1,1)", class = "b", coef = "TreatmentRatty", resp = "CCA") +
  set_prior("normal(1,1)", class = "b", coef = "Year2018", resp = "CCA") +
  set_prior("normal(0,1)", class = "b", coef = "Year2021", resp = "CCA") +
  set_prior("normal(-1,1)", class = "b", coef = "TreatmentRatty:Year2018", resp = "CCA") +
  set_prior("normal(0,1)", class = "b", coef = "TreatmentRatty:Year2021", resp = "CCA") +
    #Hard coral: drop in 2018
  set_prior("normal(0,1)", class = "b", coef = "TreatmentRatty", resp = "Hardcoral") +
  set_prior("normal(-1,1)", class = "b", coef = "Year2018", resp = "Hardcoral") +
  set_prior("normal(0,1)", class = "b", coef = "Year2021", resp = "Hardcoral") +
  set_prior("normal(0,1)", class = "b", coef = "TreatmentRatty:Year2018", resp = "Hardcoral") +
  set_prior("normal(0,1)", class = "b", coef = "TreatmentRatty:Year2021", resp = "Hardcoral") +
    #Pavement: increase in 2018 only around ratty
  set_prior("normal(0,1)", class = "b", coef = "TreatmentRatty", resp = "Pavement") +
  set_prior("normal(1,1)", class = "b", coef = "Year2018", resp = "Pavement") +
  set_prior("normal(0,1)", class = "b", coef = "Year2021", resp = "Pavement") +
  set_prior("normal(1,1)", class = "b", coef = "TreatmentRatty:Year2018", resp = "Pavement") +
  set_prior("normal(0,1)", class = "b", coef = "TreatmentRatty:Year2021", resp = "Pavement") +
  #rubble - not sure...
   set_prior("normal(0,1)", class = "b", coef = "TreatmentRatty", resp = "Rubble") +
  set_prior("normal(0,1)", class = "b", coef = "Year2018", resp = "Rubble") +
  set_prior("normal(0,1)", class = "b", coef = "Year2021", resp = "Rubble") +
  set_prior("normal(0,1)", class = "b", coef = "TreatmentRatty:Year2018", resp = "Rubble") +
  set_prior("normal(0,1)", class = "b", coef = "TreatmentRatty:Year2021", resp = "Rubble") 

#run model:
benthic_mod_beta <- brm(benthic_mv_isl_beta + 
                  set_rescor(FALSE), #must be set to false because not gaussian or student t model
                data=uvc_dat_group_trans_wide_prop_scale2,
              iter = 3000, warmup = 1000, cores=4, chains = 4, 
              prior = benthic_prior_bb,
              sample_prior="yes",
            control = list(adapt_delta = 0.99,max_treedepth = 15),
                file = "../output/brms/benthic_mod_beta")
print(benthic_mod_beta) #worked

#check plots:
plot(benthic_mod_beta, ask = FALSE)

pp_check(benthic_mod_beta, resp = "CCA", ndraws = 100)
pp_check(benthic_mod_beta, resp = "Hardcoral", ndraws = 100)
pp_check(benthic_mod_beta, resp = "Pavement", ndraws = 100)
pp_check(benthic_mod_beta, resp = "Halimeda", ndraws = 100) ##not sampling quite high enough at 0. compared to 0-inflated model for Halimeda and got same results, so can keep this one to have all groups together. 
pp_check(benthic_mod_beta, resp = "Rubble", ndraws = 100)


```


#extract model estimates
```{r}

#hard coral----
#to report median estimates for each group, on response scale: 
benthic_mod_beta %>% 
  emmeans(~ Treatment|Year,
          type = "response",
          resp = "Hardcoral") 
#median coral cover estimated to be 31% in 2015 around both birdy and ratty islands, drops to 16.6 and 20% in 2018, then back up to 34.2 and 31.4% in 2021)

#relative increase in cover (2018 to 2021) = 
(0.314 - 0.166)/0.166 #89%
(0.342 - 0.200)/0.200 #71%

#relative decrease in cover (2015 to 2018)= 
(0.310 - 0.166)/0.310 #46.5%
(0.311 - 0.200)/0.311 #35.7%


#to report raw estimates of % difference between treatment-year combos, on response scale: 
benthic_mod_beta %>% 
  emmeans(~ Treatment*Year,
          at = list(Treatment = c("Ratty")),
          epred = TRUE,
          re_formula = NA,
          resp="Hardcoral") %>% 
    contrast(method = "revpairwise") 
#so there is a 2.6% difference in hard coral around ratty islands from 2021 to 2015 (overlaps 0)
#13% increase from 2018 to 2021
#10% decrease 2015 to 2018


benthic_mod_beta %>% 
  emmeans(~ Treatment*Year,
          at = list(Treatment = c("Birdy")),
          epred = TRUE,
          re_formula = NA,
          resp="Hardcoral") %>% 
    contrast(method = "revpairwise") 
#so there is a 0% difference in hard coral around birdy islands from 2021 to 2015 (overlaps 0)
#13.9% increase from 2018 to 2021
#13.5% decrease 2015 to 2018

#averaged over treatment:
benthic_mod_beta%>%
emmeans("Year", 
        type="response",
        resp="Hardcoral",
         epred = TRUE,
          re_formula = NA)%>%
  contrast("revpairwise")
# contrast            estimate lower.HPD upper.HPD
# Year2018 - Year2015  -0.1195   -0.2108   -0.0324
# Year2021 - Year2015   0.0143   -0.0374    0.0721
# Year2021 - Year2018   0.1371    0.0412    0.2300


#compare treatments within each year:
benthic_mod_beta %>% 
  emmeans(~ Treatment*Year,
          at = list(Year = c("2015")),
          epred = TRUE,
          re_formula = NA,
          resp="Hardcoral") %>% 
    contrast(method = "revpairwise") 
#no difference

benthic_mod_beta %>% 
  emmeans(~ Treatment*Year,
          at = list(Year = c("2018")),
          epred = TRUE,
          re_formula = NA,
          resp="Hardcoral") %>% 
    contrast(method = "revpairwise") 
#no difference

benthic_mod_beta %>% 
  emmeans(~ Treatment*Year,
          at = list(Year = c("2021")),
          epred = TRUE,
          re_formula = NA,
          resp="Hardcoral") %>% 
    contrast(method = "revpairwise") 
#no difference


#####to report odds ratios (because beta regression): 
benthic_mod_beta %>% 
   emmeans(~ Treatment|Year,
          type = "response",
          resp = "Hardcoral") %>%
  contrast("pairwise")
#birdy and ratty equivalent in every year (odds ratio overlaps 1)

benthic_mod_beta %>% 
   emmeans(~ Year|Treatment,
          type = "response",
          resp = "Hardcoral") %>%
  contrast("revpairwise")
#2021 equivalent to 2015, 2018 is lower*


#halimeda----

#to report median estimates for each group, on response scale: 
benthic_mod_beta %>% 
  emmeans(~ Treatment|Year,
          type = "response",
          resp = "Halimeda") 

#####to report estimates of % difference between treatment-year combos, on response scale: 
benthic_mod_beta %>% 
  emmeans(~ Treatment*Year,
          at = list(Treatment = c("Ratty", "Birdy")),
          epred = TRUE,
          re_formula = NA,
          resp="Halimeda") %>% 
    contrast(method = "revpairwise") 


#####to report odds ratios (because beta regression): 
benthic_mod_beta %>% 
   emmeans(~ Treatment|Year,
          type = "response",
          resp = "Halimeda") %>%
  contrast("pairwise")


benthic_mod_beta %>% 
   emmeans(~ Year|Treatment,
          type = "response",
          resp = "Halimeda") %>%
  contrast("revpairwise")


#CCA----

#####to report median estimates for each group, on response scale: 
benthic_mod_beta %>% 
  emmeans(~ Treatment|Year,
          type = "response",
          resp = "CCA") 

#####to report estimates of % difference between treatment-year combos, on response scale: 
benthic_mod_beta %>% 
  emmeans(~ Treatment*Year,
          at = list(Treatment = c("Ratty", "Birdy")),
          epred = TRUE,
          re_formula = NA,
          resp="CCA") %>% 
    contrast(method = "revpairwise") 


#####to report odds ratios (because beta regression): 
benthic_mod_beta %>% 
   emmeans(~ Treatment|Year,
          type = "response",
          resp = "CCA") %>%
  contrast("pairwise")

benthic_mod_beta %>% 
   emmeans(~ Year|Treatment,
          type = "response",
          resp = "CCA") %>%
  contrast("revpairwise")



#Pavement----

#####to report median estimates for each group, on response scale: 
benthic_mod_beta %>% 
  emmeans(~ Treatment|Year,
          type = "response",
          resp = "Pavement") 

#####to report estimates of % difference between treatment-year combos, on response scale: 
benthic_mod_beta %>% 
  emmeans(~ Treatment*Year,
          at = list(Treatment = c("Ratty", "Birdy")),
          epred = TRUE,
          re_formula = NA,
          resp="Pavement") %>% 
    contrast(method = "revpairwise") 


#####to report odds ratios (because beta regression): 
benthic_mod_beta %>% 
   emmeans(~ Treatment|Year,
          type = "response",
          resp = "Pavement") %>%
  contrast("pairwise")

benthic_mod_beta %>% 
   emmeans(~ Year|Treatment,
          type = "response",
          resp = "Pavement") %>%
  contrast("revpairwise")
#



#Rubble----

#####to report median estimates for each group, on response scale: 
benthic_mod_beta %>% 
  emmeans(~ Treatment|Year,
          type = "response",
          resp = "Rubble") 

#####to report estimates of % difference between treatment-year combos, on response scale: 
benthic_mod_beta %>% 
  emmeans(~ Treatment*Year,
          at = list(Treatment = c("Ratty", "Birdy")),
          epred = TRUE,
          re_formula = NA,
          resp="Rubble") %>% 
    contrast(method = "revpairwise") 


#####to report odds ratios (because beta regression): 
benthic_mod_beta %>% 
   emmeans(~ Treatment|Year,
          type = "response",
          resp = "Rubble") %>%
  contrast("pairwise")

benthic_mod_beta %>% 
   emmeans(~ Year|Treatment,
          type = "response",
          resp = "Rubble") %>%
  contrast("revpairwise")

```


#Plots
```{r}
#hard coral separately:----
#plot using same technique as benthic: 
benthic_pred<-
  benthic_mod_beta %>% 
  epred_draws(newdata = expand_grid(Treatment = c("Ratty", "Birdy"),
                                    Year = c("2015", "2018", "2021")), 
                  re_formula=NA)
benthic_pred

med_pred_hc<-
  benthic_pred %>%
    filter(.category=="Hardcoral")%>%
  group_by(Treatment, Year)%>%
  summarize(med_prediction = median(.epred))%>%
  mutate( Year = as.factor(Year), 
         Treatment = as.factor(Treatment))
med_pred_hc

hard_coral_plot<-
benthic_pred %>%
  mutate(Treatment = as.factor(Treatment),
         Year = as.factor(Year))%>%
  filter(.category=="Hardcoral")%>%
    mutate(Treatment = fct_relevel(Treatment, "Birdy", "Ratty"))%>%
  ggplot(aes(x = Year, y = .epred, color = Treatment, fill = Treatment, shape = Treatment)) +
      geom_line(data = med_pred_hc, aes(x = Year, y =med_prediction, group = Treatment), alpha = .5, position = position_dodge(width = .05))+
  stat_pointinterval(point_interval=median_hdi, .width=c(.9, .7, .5), fatten_point = 2, interval_alpha = 0.2, position = position_dodge(width = .05)) +

  ylab("Proportional hard coral cover")+
scale_color_manual(values = c("#0067A5", "#BE0032"),
                                            breaks=c("Birdy",  "Ratty"),
                      labels=c("seabird islands",  "rat islands"),
                    name = "" )+
  scale_fill_manual(values = c("#0067A5", "#BE0032"),
                                            breaks=c("Birdy",  "Ratty"),
                      labels=c("seabird islands",  "rat islands"),
                    name = "" )+ 
    scale_shape_manual(values = c(19, 15),
                    breaks=c("Birdy",  "Ratty"),
                      labels=c("seabird islands",  "rat islands"),
                    name = "" )+
  theme_bw() + 
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = c(.5, .9),  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=8,  family="sans"),
         legend.text=element_text(size=8, family = "sans"),
        axis.title.y = element_text(size=8, family = "sans"),
        axis.text = element_text(size = 8, family = "sans")) 
hard_coral_plot



med_pred_nohc<-
  benthic_pred %>%
    filter(.category!="Hardcoral")%>%
  group_by(Treatment, Year, .category)%>%
  summarize(med_prediction = median(.epred))%>%
  mutate( Year = as.factor(Year), 
         Treatment = as.factor(Treatment))
med_pred_nohc

#for labels:
ann_text <- data.frame(Year = "2021",.epred = .7, Treatment = "",
                       lab = c("B. CCA", "C. Halimeda", "D. Pavement", "E. Rubble"),
                       .category = factor(c("CCA","Halimeda","Pavement", "Rubble"), 
                                          levels = c("CCA","Halimeda","Pavement", "Rubble")))
benthic_plot<-
benthic_pred %>%
  mutate(Treatment = as.factor(Treatment),
         Year = as.factor(Year))%>%
  filter(.category!="Hardcoral")%>%
  droplevels()%>%
  mutate(.category = fct_relevel(.category, "CCA", "Halimeda", "Pavement", "Rubble"))%>%
    mutate(Treatment = fct_relevel(Treatment, "Birdy", "Ratty"))%>%
   ggplot(aes(x = Year, y = .epred, color = Treatment, fill = Treatment, shape = Treatment)) +
    facet_wrap(~.category)+
  stat_pointinterval(point_interval=median_hdi, .width=c(.9, .7, .5), fatten_point = 2, interval_alpha = 0.2, position = position_dodge(width = .05)) +
    geom_line(data = med_pred_nohc, aes(x = Year, y =med_prediction, group = Treatment), alpha = .5, position = position_dodge(width = .05))+
  scale_color_manual(values = c("black","#0067A5",  "#BE0032"),
                     guide = "none")+
  scale_fill_manual(values = c("black", "#0067A5", "#BE0032"),
                                            breaks=c("Birdy",  "Ratty"),
                     guide = "none")+ 
      scale_shape_manual(values = c(19, 15, 15),
                    breaks=c("Birdy",  "Ratty"),
                      labels=c("seabird islands",  "rat islands"),
                    name = "" )+
  xlab("Year")+
  ylab("Proportional cover")+
  geom_text(data = ann_text,label = ann_text$lab, size = 9/.pt, family = "sans", fontface = "bold")+ #, hjust = 1
  theme_bw() + 
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=8,  family="sans"),
         legend.text=element_text(size=8, family = "sans"),
        axis.title.y = element_text(size=8, family = "sans"),
        axis.text = element_text(size = 8, family = "sans"),
        strip.text = element_blank()) 

benthic_plot


```



###Run NMDS for broad benthic groups
```{r}
uvc_dat_group_isl_wide

#make community matrix:
uvc_dat_group_isl_wide_sp<-
  uvc_dat_group_isl_wide %>%
  select(-c(Year, Atoll, Island, Treatment)) %>%
  rename_with(~str_remove(., 'Mean_'))

##Run NMDS-----
nmds_benthic_broad =metaMDS(uvc_dat_group_isl_wide_sp, trymax=50, k=2, autotransform=FALSE, distance = "bray")
#note: autotransform=FALSE to keep consistent with GCB paper

nmds_benthic_broad$stress # stress = 0.1593766

##Extract site and nmds_spp and ggplot--------
spp.sc <- scores(nmds_benthic_broad, display = "species", shrink = FALSE) 
spp.sc
site.sc <- scores(nmds_benthic_broad, display = "sites", shrink = FALSE) 
site.sc

#merge site.sc with metadata from dataframe
#need combo column: 
uvc_dat_group_isl_wide_ty<-
  uvc_dat_group_isl_wide %>%
  unite("Treatment_Year", c(Treatment, Year), remove = FALSE)%>%
  relocate(Treatment_Year, .after = Treatment)

nmds_benthic_broad_site_scores<-
  bind_cols(uvc_dat_group_isl_wide_ty[1:5],
                    as_tibble(site.sc))

#extract species scores
species.scores <- as.data.frame(scores(nmds_benthic_broad, "species"))  #Using the scores function from vegan to extract the species scores and convert to a data.frame
species.scores<-
  species.scores%>%
  rownames_to_column(var="Species") # create a column of species, from the rownames of species.scores
head(species.scores)  #look at the data


#get convex hulls for polygons
hull_nr2015<-nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Birdy_2015", ][chull(nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Birdy_2015", ]$NMDS1, nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Birdy_2015", ]$NMDS2), ] 

hull_nr2018<-nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Birdy_2018", ][chull(nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Birdy_2018", ]$NMDS1, nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Birdy_2018", ]$NMDS2), ] 

hull_nr2021<-nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Birdy_2021", ][chull(nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Birdy_2021", ]$NMDS1, nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Birdy_2021", ]$NMDS2), ] 

hull_r2018<-nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Ratty_2018", ][chull(nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Ratty_2018", ]$NMDS1, nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Ratty_2018", ]$NMDS2), ] 

hull_r2015<-nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Ratty_2015", ][chull(nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Ratty_2015", ]$NMDS1, nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Ratty_2015", ]$NMDS2), ] 

hull_r2021<-nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Ratty_2021", ][chull(nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Ratty_2021", ]$NMDS1, nmds_benthic_broad_site_scores[nmds_benthic_broad_site_scores$Treatment_Year == "Ratty_2021", ]$NMDS2), ] 


hull.data <- rbind(hull_nr2015, hull_nr2018, hull_nr2021, hull_r2021,  hull_r2018, hull_r2015)  #combine grp.a and grp.b
hull.data

#rename species:
species.scores2<-
  species.scores%>%
  mutate(Species = case_when(Species == "Other_Benthos"~ "Other",
                             Species == "Soft_coral"~ "Soft coral",
                             Species == "Hard_coral"~ "Hard coral",
                             TRUE ~ as.character(Species)))
species.scores2

#get centroids to plot arrows
ord.fit.benth<-envfit(nmds_benthic_broad~Treatment_Year, data = uvc_dat_group_isl_wide_ty)
ord.fit.benth
#and check correlations to see what's likely driving patterns:
cor(uvc_dat_group_isl_wide_sp, scores(nmds_benthic_broad, dis="si"))
#birdy islands shift towards negative NMDS1 - Halimeda and CCA have strongest negative associations with NMDS1. Pavement has positive corr with NMDS1. 

#if want to plot:
# geom_segment(aes(x = 0.1467, y = 0.0064, xend = -0.6037, yend = 0.0936), colour = "#0067A5", linetype=1)+ #from ord.fit
#    geom_segment(aes(x = -0.6037, y = 0.0936, xend = -0.1646, yend = 0.0624), colour = "#0067A5", linetype=1, arrow =   arrow(length = unit(0.1, "inches")))+ #from ord.fit
#        geom_segment(aes(x = 0.2093, y = -0.0355, xend = 0.1615, yend = -0.1243), colour = "#BE0032", linetype=1)+ #from ord.fit
#    geom_segment(aes(x = 0.1615, y = -0.1243, xend = 0.1771, yend = -0.0078), colour = "#BE0032", linetype=1, arrow =   arrow(length = unit(0.1, "inches")))+ 


nmds_benth_plot<-
ggplot() + 
 geom_polygon(data=hull.data,aes(x=NMDS1,y=NMDS2,fill=Treatment_Year,group=Treatment_Year, colour = Treatment_Year), alpha = 0.15, linetype=1, lwd = .1) + # add the 
  geom_text(data=species.scores2,aes(x=NMDS1,y=NMDS2,label=Species), size = 3) +  # add the species labels - 
  geom_point(data=nmds_benthic_broad_site_scores,aes(x=NMDS1,y=NMDS2,colour=Treatment_Year, fill = Treatment_Year, pch = Treatment_Year), stat="identity", size=5, alpha = .5) +
   scale_colour_manual(name = "Year and Treatment",
                      labels = c("2015 seabird", "2018 seabird", "2021 seabird", 
                                 "2015 rat", "2018 rat", "2021 rat"),
                      values = c("#0067A5", "#0067A5", "#0067A5", 
                                 "#BE0032", "#BE0032", "#BE0032"), guide = "none") +   
     scale_fill_manual(name = "Year and Treatment",
                      labels = c("2015 seabird", "2018 seabird", "2021 seabird", 
                                 "2015 rat", "2018 rat", "2021 rat"),
                      values = c("#0067A5", "#0067A5", "#0067A5", 
                                 "#BE0032", "#BE0032", "#BE0032") ) +  
  scale_shape_manual(name = "Year and Treatment",
                      labels = c("2015 seabird", "2018 seabird", "2021 seabird", 
                                 "2015 rat", "2018 rat", "2021 rat"),
                     values = c(21, 24, 22, 21, 24, 22))+
 # guides(fill = guide_legend(ncol = 2))+
  theme_bw() + 
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), #remove gray boxes
        text = element_text(size=12),
        legend.title = element_blank(), #remove legend title
        legend.box.background = element_rect(colour = "black", fill='white', linetype='solid', size=1),
        legend.text=element_text(size=12))
       # legend.justification=c(1,.9), legend.position=c(1,.9))  #  fix legend
      
nmds_benth_plot


```

## Run brms on dissimilarity metric
```{r}
#run BRMS: Bray (use beta because between 0 and 1)----
#default prior - had no idea what to expect, and sampling was better without one. 

dist_2015_bray_mod_beta <- brm(bf(Distance_to_2015 ~ Treatment*Year +(1|Atoll),
                                      family = Beta()),
                data=benthic_dist_mat_bray_diff_no15,
              iter = 3000, warmup = 1000, cores=4, chains = 4, 
                control = list(adapt_delta = 0.999, max_treedepth = 15), 
              #sample_prior="yes",
                file = "../output/brms/dist_2015_bray_mod_beta")
print(dist_2015_bray_mod_beta) 

plot(dist_2015_bray_mod_beta, ask = FALSE)
pp_check(dist_2015_bray_mod_beta) #pretty good


##extract estimates: ----
#####to report median estimates for each group, on response scale: 
dist_2015_bray_mod_beta %>% 
  emmeans(~ Treatment|Year,
          type = "response") 
#birdy islands changed almost twice as much as ratty islands. BUT, downward trend, versus stable/upward trend in ratty communities....

(0.456-0.242)/0.242 #0.8842975
(0.361-0.456)/0.456 #-0.2083333 - birdy reduction in dissimilarity by 20% from 2018 to 2021
(0.274-0.242)/0.242 #0.1322314 - but ratty increase in dissimilarity by 13%...


#####to report estimates of difference between treatment-year combos, on response scale: 
dist_2015_bray_mod_beta %>% 
  emmeans(~ Treatment*Year,
          at = list(Treatment = c("Ratty", "Birdy")),
          epred = TRUE,
          re_formula = NA) %>% 
    contrast(method = "revpairwise") 

#####to report odds ratios (because beta regression): 
dist_2015_bray_mod_beta %>% 
   emmeans(~ Treatment|Year,
          type = "response") %>%
  contrast("pairwise")

dist_2015_bray_mod_beta %>% 
   emmeans(~ Year|Treatment,
          type = "response") %>%
  contrast("pairwise")

dist_2015_bray_mod_beta %>% 
   emmeans(~ Year|Treatment,
          type = "response") %>%
  contrast("revpairwise")

```


##Plot disimilarity predictions
```{r}

pred_dist_bray<-
  dist_2015_bray_mod_beta %>% 
  epred_draws(newdata = expand_grid(Treatment = c("Birdy", "Ratty"), Year = c(2018, 2021)), 
                  re_formula=NA) %>%
  mutate(Treatment_Year = str_c(Treatment, Year, sep ="_"))
pred_dist_bray


dist_2015_bray_mod_plus_raw_plot<-
  pred_dist_bray %>%
 mutate(Treatment = as.factor(Treatment),
         Year = as.factor(Year),
         Treatment_Year = as.factor(Treatment_Year))%>%
    mutate(Treatment_Year = fct_relevel(Treatment_Year, "Birdy_2018", "Ratty_2018", "Birdy_2021", "Ratty_2021"))%>%
  ggplot(aes(color=Treatment, fill=Treatment, shape = Treatment)) +
  geom_point(data = benthic_dist_mat_bray_diff_no15[benthic_dist_mat_bray_diff_no15$Year=="2018",], aes(x=Year, y = Distance_to_2015, ), alpha = .5, 
             position = position_nudge(x = .05)) + 
    geom_point(data = benthic_dist_mat_bray_diff_no15[benthic_dist_mat_bray_diff_no15$Year=="2021",], aes(x=Year, y = Distance_to_2015, ), alpha = .5, 
             position = position_nudge(x = -.05)) + 
  geom_line(data = benthic_dist_mat_bray_diff_no15, aes(group=Island,x=Year, y =Distance_to_2015), alpha = .5, 
           position = position_nudge(x = c(-.05, .05, -.05, .05, -.05, .05, -.05, .05, -.05, .05,
                                           -.05, .05, -.05, .05, -.05, .05, -.05, .05, -.05, .05,
                                           .05, -.05)))+
   stat_pointinterval(aes(y = .epred, x = Year), 
               point_interval=median_hdi, .width=c(.9, .7), fatten_point = 4, interval_alpha = .7, point_alpha = 1,
               position = position_dodge(width = .07)
               ) + 
scale_color_manual(values = c("#0067A5", "#BE0032"),
                                            breaks=c("Birdy",  "Ratty"),
                      labels=c("seabird islands",  "rat islands"),
                    name = "" )+
  scale_fill_manual(values = c("#0067A5", "#BE0032"),
                                            breaks=c("Birdy",  "Ratty"),
                      labels=c("seabird islands",  "rat islands"),
                    name = "" )+ 
  scale_shape_manual(values = c(19, 15),
                    breaks=c("Birdy",  "Ratty"),
                      labels=c("seabird islands",  "rat islands"),
                    name = "" )+
  xlab("")+
  ylab("Distance to 2015")+
#design:  
theme_bw() + 
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        axis.ticks.y = element_blank(),
        legend.position = c(.85,.92),  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=8,  family="sans"),
         legend.text=element_text(size=8, family = "sans"),
        axis.title.y = element_text(size=8, family = "sans"),
        axis.text = element_text(size = 8, family = "sans"))

dist_2015_bray_mod_plus_raw_plot

```


##combine plots and save - coral recruits + cover
```{r}
#from coral_recruitment.Rmd:
all_recruit_plot_mult_hdis
acrop_recruit_plot_mult_hdis

#from coral_group_recover_analysis.Rmd:
acrop_plot_mult_hdis

#from this file: 
hard_coral_plot

coral_recruit_cover_plot<-plot_grid(acrop_recruit_plot_mult_hdis, acrop_plot_mult_hdis,
                                    all_recruit_plot_mult_hdis, hard_coral_plot,
                                    nrow=2, rel_widths = c(.6, 1, .6, 1), 
                                    labels = "AUTO", label_x = c(.15, .1, .15, .1), 
                                    label_y = c(.96, .96, .96, .96), label_fontface = "bold", label_size = 9, label_fontfamily = "sans")
coral_recruit_cover_plot


#ggsave(filename = "../output/figures/coral_recruit_cover_plot.jpg", 
#       plot = coral_recruit_cover_plot,
##       width = 8,
#       height = 6,
#       units = "in",
#      dpi = 300)


#sci advances:
ggsave(filename = "../output/figures/coral_recruit_cover_plots.pdf", 
       plot = coral_recruit_cover_plot,
       width = 7.25,
       height = 5.25,
       units = "in",
       family = "sans",
       useDingbats=FALSE,
      dpi = 1200)

```


#combine plots - other benthic groups
```{r}
dist_2015_bray_mod_plus_raw_plot
benthic_plot


benthic_distance_cover_plot<-plot_grid(
  plot_grid(NULL, dist_2015_bray_mod_plus_raw_plot, NULL, nrow = 1, rel_widths = c(0.33, 1, 0.33)),
  plot_grid(benthic_plot),
  nrow = 2,
  labels = "A", rel_heights = c(.65, 1), label_x = .27, label_y =.97, label_fontface = "bold", label_size=9, label_fontfamily = "sans"
)
benthic_distance_cover_plot


#ggsave(filename = "../output/figures/benthic_distance_cover_plot.jpg", 
#       plot = benthic_distance_cover_plot,
#       width = 8,
#       height = 8,
#       units = "in",
#      dpi = 300)

#sci advances:
ggsave(filename = "../output/figures/benthic_distance_cover_plot.pdf", 
       plot = benthic_distance_cover_plot,
       width = 7.25,
       height = 7.25,
       units = "in",
       family = "sans",
       useDingbats=FALSE,
      dpi = 1200)

```



##combine nmds plots (supp fig)
```{r}
#from this file:
nmds_benth_plot

#from coral_group_recovery_analysis:
nmds_coral_group_plot

nmds_plots<-plot_grid(nmds_coral_group_plot, nmds_benth_plot,
                                    nrow=2,axis = "l", align = "hv",
                                    labels = "AUTO", label_x = c(.1, .1), 
                                    label_y = c(.98, .98), label_fontface = "bold")
nmds_plots


ggsave(filename = "../output/figures/nmds_plots.jpg", 
       plot = nmds_plots,
       width = 7,
       height = 8,
       units = "in",
      dpi = 1200)


```

