---
title: "coral_growth_rte"
author: "CEB"
date: '2023-03-20'
output: html_document
---


## load packages
```{r}
library(tidyverse)

library(cowplot) #for combining plots

#bayesian analyses:
library(brms)
library(tidybayes)

#extracting effects
library(emmeans)

```


## load data
```{r}
load("../data/R_data/coral_RTE_growth_data.RData")
#rte_dat_diff_w_init_size_cs

```


#set plot theme
```{r}
theme_casey<-
  theme_bw()+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        text = element_text(size = 14, family = "Arial"),
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA)
        )

theme_set(theme_casey) 
  
  
```


##run Bayesian model
```{r}

###set prior----
rte_gr_prior<-
     set_prior("normal(1, .5)", class = "b", coef = "Transplant_treatmentrlbirdy")+ #definitely expect positive effect, approx 4 times, but kept slightly lower so consistent with natural growth models...
   set_prior("normal(.5, 1)", class = "b", coef = "Origin_treatmentrlbirdy")+ #origin treatment less sure of - Savage shows very little effect of origin..
    set_prior("normal(.5, 1)", class = "b", coef = "Origin_treatmentrlbirdy:Transplant_treatmentrlbirdy")+ #interaction less sure of -  Savage shows very little effect (although maybe slight interaction).
    set_prior("normal(0, 1)", class = "b", coef = "Previous_surface_area_cs")+ #really not sure on this, expect larger colonies to grow more absolute, but smaller proportionally. So go with 0
    set_prior("normal(4.6, 1)", class = "Intercept") ##max growth from Pratchett (assuming pi*r^2) for Acropora = exp(7.2) (1333 cm/year). mean growth = 4.6 (100)


####run model----
rte_gr_mod_log<- brm(
 log(diff_SA_year)~Origin_treatmentrl*Transplant_treatmentrl + Previous_surface_area_cs + (1|Atoll/Origin_colony_unique_ID) + (1|Year),
  data = rte_dat_diff_w_init_size_cs, 
  iter = 3000, warmup = 1000, chains = 4, cores = 4,
  control = list(adapt_delta = 0.999, max_treedepth = 15), 
  prior = rte_gr_prior,
   sample_prior="yes",
      file = "../output/brms/rte_gr_mod_log") 
print(rte_gr_mod_log) #quick and no divergent trans
#looks reasonable
#only effect that doesn't overlap 0 at 95% CI = transplant treatment

##plots to check model:----
pp_check(rte_gr_mod_log)

plot(rte_gr_mod_log, ask = FALSE)

```

##extract model estimates
```{r}


##extract emmeans----
rte_gr_mod_log.rg <- update(ref_grid(rte_gr_mod_log), tran = "log") #THIS LINE IS CLUTCH*** Now don't have to use link transformations, can use log response and still backtransform with emmeans

#compare to rat-rat as reference:
rte_gr_mod_log.rg%>%
emmeans(c("Origin_treatmentrl", "Transplant_treatmentrl"),
        type="response")%>%
      contrast("trt.vs.ctrl")
# birdy ratty / ratty ratty  1.62      0.55      3.23
# ratty birdy / ratty ratty  2.58      1.47      3.97
# birdy birdy / ratty ratty  2.59      1.22      4.58


#full output for interaction effect:
rte_gr_mod_log.rg%>%
emmeans(c("Origin_treatmentrl", "Transplant_treatmentrl"),
        type="response")%>%
      contrast("revpairwise")


#averaged over transplant treatment:
rte_gr_mod_log.rg%>%
emmeans("Origin_treatmentrl", 
        by=c("Previous_surface_area_cs"),
        type="response")%>%
  contrast("trt.vs.ctrl")
#birdy / ratty  1.28     0.662       2.1


#averaged over origin treatment:
rte_gr_mod_log.rg%>%
emmeans("Transplant_treatmentrl", 
        by=c("Previous_surface_area_cs"),
        type="response")%>%
  contrast("trt.vs.ctrl")
# birdy / ratty  2.03      1.17      3.17


###each group: 
rte_gr_mod_log.rg%>%
emmeans("Transplant_treatmentrl", 
        by=c("Origin_treatmentrl", "Previous_surface_area_cs"),
        type="response")
# ratty - ratty       33.0     
# ratty - birdy       85.4     
# birdy - ratty       54.2  
# birdy - birdy       85.2 


#get estimates
get_variables(rte_gr_mod_log)
rte_gr_mod_log%>%
 gather_draws(`b_Origin_treatmentrlbirdy:Transplant_treatmentrlbirdy`) %>%
  median_hdi(.width=c(.95))
#trend towards negative interaction, although 95% HDI overlaps 0.


```


#create plot - posterior distributions by group
```{r}
#posterior distributions by group----
#log:
rte_growth_group_estimates_plot<-
rte_gr_mod_log %>% 
  epred_draws(newdata = expand_grid(Transplant_treatmentrl = c("birdy", "ratty"), 
                                    Origin_treatmentrl = c("birdy", "ratty"), 
                                    Previous_surface_area_cs = 0, 
                                    reps = 100),
                  re_formula=NA) %>%
    mutate(Origin_transplant = str_c(Origin_treatmentrl, Transplant_treatmentrl, sep ="_"))%>%
   mutate(Origin_transplant = as.factor(Origin_transplant))%>%
  mutate(Origin_transplant = fct_relevel(Origin_transplant, c("birdy_birdy",  "ratty_birdy", "birdy_ratty",  "ratty_ratty")))%>%
  mutate(Origin_transplantrl2 = fct_relevel(Origin_transplant, c( "ratty_ratty", "birdy_ratty",  "ratty_birdy","birdy_birdy" )))%>%
    mutate(Origin_transplantrl3 = fct_relevel(Origin_transplant, c(  "ratty_birdy",  "birdy_ratty", "ratty_ratty", "birdy_birdy" )))%>%
  ggplot(aes(x = .epred, color = Origin_transplant, fill = Origin_transplant)) +
  stat_slab(aes(x = .epred, color = Origin_transplantrl3, fill = Origin_transplantrl3), point_interval=median_hdi, slab_alpha = .4) + #use relevel only because then blue is on top. 
   stat_pointinterval(aes(x = .epred, color = Origin_transplantrl2, fill = Origin_transplantrl2), #use relevel 2 so in correct order
.width=c(.9, .7), position = position_dodge(width = .3, preserve = "single"), shape = 24) +
  scale_color_manual(values = c("#0067A5", "#A1CAF1", "#F99379", "#BE0032"),
                    name = "",
                                            breaks=c("birdy_birdy",  "ratty_birdy", "birdy_ratty",  "ratty_ratty"),
                       labels=c("seabird to seabird", "rat to seabird", "seabird to rat", "rat to rat"))+
  scale_fill_manual(values = c("#0067A5", "#A1CAF1", "#F99379", "#BE0032"),
                    name = "",
                                            breaks=c("birdy_birdy",  "ratty_birdy", "birdy_ratty",  "ratty_ratty"),
                       labels=c("seabird to seabird", "rat to seabird", "seabird to rat", "rat to rat")
                    )+ #light blue = #A1CAF1, light red/pink = #F99379, orange = #F38400, purple = #875692
    xlab(expression(paste("Coral growth rate (log cm"^"2"*"year"^"-1"*")")))+
  scale_y_continuous(lim=c(-.15,1), breaks = c(0, .5,  1.0))+
  ylab("Posterior density")+
  theme_bw() + 
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = c(.8, .85),  
      # legend.title=element_blank(),
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
              text=element_text(size=8,  family="sans"),
         legend.text=element_text(size=8, family = "sans"),
        axis.title = element_text(size=8, family = "sans"),
        axis.text = element_text(size = 8, family = "sans")) 
rte_growth_group_estimates_plot



```


#create plot - combined effect sizes for rte and natural
```{r}

#make sure have both brms models:
natural_growth_mod_log<-readRDS("../output/brms/natural_growth_mod_log.RDS")
rte_gr_mod_log<-readRDS("../output/brms/rte_gr_mod_log.RDS")

natural_growth_mod_log
natural_growth_mod_log.rg <- update(ref_grid(natural_growth_mod_log), tran = "log") 

rte_gr_mod_log
rte_gr_mod_log.rg <- update(ref_grid(rte_gr_mod_log), tran = "log") 


#get estimates and HPDs for both natural and rte:
nat_pred_gr_7<-natural_growth_mod_log.rg%>%
  emmeans("Treatmentrl", 
        by=c("Previous_surface_area_cs"),
        type="response")%>%
  contrast("trt.vs.ctrl", level = .7)%>%
  as.data.frame()

nat_pred_gr_9<-natural_growth_mod_log.rg%>%
  emmeans("Treatmentrl", 
        by=c("Previous_surface_area_cs"),
        type="response")%>%
  contrast("trt.vs.ctrl", level = .9)%>%
  as.data.frame()


rte_origin_pred_gr_7<-rte_gr_mod_log.rg%>%
emmeans("Origin_treatmentrl", 
        by=c("Previous_surface_area_cs"),
        type="response")%>%
  contrast("trt.vs.ctrl", level = .7)%>%
  as.data.frame()


rte_origin_pred_gr_9<-rte_gr_mod_log.rg%>%
emmeans("Origin_treatmentrl", 
        by=c("Previous_surface_area_cs"),
        type="response")%>%
  contrast("trt.vs.ctrl", level = .9)%>%
  as.data.frame()


rte_trans_pred_gr_7<-rte_gr_mod_log.rg%>%
emmeans("Transplant_treatmentrl", 
        by=c("Previous_surface_area_cs"),
        type="response")%>%
  contrast("trt.vs.ctrl", level = .7)%>%
  as.data.frame()


rte_trans_pred_gr_9<-rte_gr_mod_log.rg%>%
    emmeans("Transplant_treatmentrl", 
        by=c("Previous_surface_area_cs"),
        type="response")%>%
  contrast("trt.vs.ctrl", level = .9)%>%
  as.data.frame()

nat_pred_gr_7
nat_pred_gr_9
rte_origin_pred_gr_7
rte_origin_pred_gr_9
rte_trans_pred_gr_7
rte_trans_pred_gr_9

#combine estimates:
rte_nat_pred_est<-data.frame(effect = c( 'origin', 'origin', 'transplant', 'transplant', 'natural', 'natural'),
                             type = c('experimental', 'experimental', 'experimental', 'experimental', 'natural' , 'natural' ),
                         ratio = c(rte_origin_pred_gr_7$ratio, rte_origin_pred_gr_7$ratio, 
                                   rte_trans_pred_gr_7$ratio, rte_trans_pred_gr_7$ratio,
                                   nat_pred_gr_7$ratio, nat_pred_gr_7$ratio), #effect size is the same regardless of interval, so can use either for these
                         low = c (rte_origin_pred_gr_9$lower.HPD, rte_origin_pred_gr_7$lower.HPD, 
                                  rte_trans_pred_gr_9$lower.HPD, rte_trans_pred_gr_7$lower.HPD,
                                  nat_pred_gr_9$lower.HPD, nat_pred_gr_7$lower.HPD),
                         up = c( rte_origin_pred_gr_9$upper.HPD, rte_origin_pred_gr_7$upper.HPD, 
                                 rte_trans_pred_gr_9$upper.HPD, rte_trans_pred_gr_7$upper.HPD,
                                 nat_pred_gr_9$upper.HPD, nat_pred_gr_7$upper.HPD),
                         level = c( .9, .7, .9, .7, .9, .7))
rte_nat_pred_est



growth_emmeans_effect_plot<-
rte_nat_pred_est %>%
  mutate(effect = fct_relevel(effect, c("origin", "transplant", "natural")))%>%
ggplot(aes(x = effect, y = ratio,fill = after_stat(abs(x) > 1), color = after_stat(abs(x) > 1)))+
    geom_hline(yintercept=1, lty=2, alpha = .8, color = "#BE0032")+
  geom_errorbar(aes(ymin = low, ymax = up), width = 0, size = c(1,2, 1, 2, 1, 2), alpha = .7)+
    geom_point(aes(shape = type), size =5, alpha = .9)+
    scale_color_manual(values = c("darkgray", "#0067A5"))+ #0067A5 #A1CAF1
      scale_fill_manual(values = c("darkgray", "#0067A5"))+ #0067A5 #A1CAF1
    scale_shape_manual(values = c(24, 21),
                    name = "",
                                            breaks=c("experimental",  "natural"),
                       labels=c("experimental colony", "natural colony"))+
  xlab("")+ #xlab("seabird vs. rat")+
      guides(fill = "none", color = "none", size = "none") + 
  scale_x_discrete(labels = c("Origin treatment\n(seabird vs rat)", "Transplant treatment\n(seabird vs rat)", "Natural\n(seabird vs rat)"))+
  ylab("Multiplicative effect of seabirds on coral growth")+
   theme_bw() + 
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = c(.3,.9),
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=8,  family="sans"),
         legend.text=element_text(size=8, family = "sans"),
        axis.title.y = element_text(size=8, family = "sans"),
        axis.text = element_text(size = 8, family = "sans")) 

growth_emmeans_effect_plot


```


##combine all growth plots (FIGURE 2)
```{r}

#from coral_individual_isotopes_plus_growth:
iso_gr_rte_line_plot

#from coral_growth_natural.Rmd:
natural_growth_group_estimates_plot

#from this file: 
growth_emmeans_effect_plot
rte_growth_group_estimates_plot


growth_plots<-plot_grid(iso_gr_rte_line_plot, growth_emmeans_effect_plot, 
                        rte_growth_group_estimates_plot, natural_growth_group_estimates_plot,
                        labels = "AUTO", nrow = 2, ncol = 2,
                        label_x = c(.13, .11, .13, .13), label_y = c(.97, .97, .97, .97),
                        label_fontface = "bold", label_size = 9, label_fontfamily = "sans")
growth_plots


#ggsave(filename = "../output/figures/growth_plots.jpg", 
#       plot = growth_plots,
#       width = 8,
#       height = 8,
#       units = "in",
#      dpi = 300)

#sci advances:
ggsave(filename = "../output/figures/growth_plots.pdf", 
       plot = growth_plots,
       width = 7.25,
       height = 7.25,
       units = "in",
       family = "sans",
       useDingbats=FALSE,
      dpi = 1200)

```


